
FROM node:22-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./
RUN npm install

# Copyproject
COPY . .

RUN npm run build

# port
EXPOSE 5173

# Start cmd
CMD ["npm", "run", "preview", "--", "--host", "0.0.0.0", "--port", "5173"]