events {}

http {
    client_max_body_size 50M;

    server {
        listen 80;

      
        location / {
            proxy_pass http://frontend:5173;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/ {
            proxy_pass http://backend:5000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /storage/ {
            proxy_pass http://minio:9000/;
            proxy_set_header Host $host;
            
            # This ensures PDFs/Images open in tab instead of downloading
            proxy_hide_header Content-Disposition;
            add_header Content-Disposition "inline";
        }
    }
}