events {}

http {
    server {
        listen 80;

        # location /UI {
        #     proxy_pass http://frontend:3000;
        # }

        
        location /api/ {
            proxy_pass http://backend:5000/;
            proxy_set_header Host $host;
        }

       
        location /storage/ {
            proxy_pass http://minio:9000/;
            proxy_set_header Host $host;
        }
    }
}